version: "3.9"
services:
  latex_docker:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../.vscode:/code/latex/.vscode
      - ../src:/code/latex/src
      - ../Makefile:/code/latex/Makefile

