version: "3.9"
services:
  latex_docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latexmk
    tty: true
    volumes:
      - ../.vscode:/code/.vscode
      - ../src:/code/src
      - ../Makefile:/code/Makefile

